dbfilename redis_queue.rdb
dir /Users/sanskargupta/frappe_docker/bench/config/pids
pidfile /Users/sanskargupta/frappe_docker/bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/sanskargupta/frappe_docker/bench/config/redis_queue.acl
