[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
user=root

[program:nginx]
command=/usr/local/bin/railway-nginx-entrypoint.sh
priority=10
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=frappe

[program:gunicorn]
command=/home/frappe/frappe-bench/env/bin/gunicorn --chdir=/home/frappe/frappe-bench/sites --bind=0.0.0.0:8000 --threads=4 --workers=2 --worker-class=gthread --worker-tmp-dir=/dev/shm --timeout=120 --preload frappe.app:application
priority=20
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=frappe

[program:websocket]
command=node /home/frappe/frappe-bench/apps/frappe/socketio.js
priority=30
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=frappe

[program:queue-short]
command=/home/frappe/frappe-bench/env/bin/bench worker --queue short,default
priority=40
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=frappe

[program:queue-long]
command=/home/frappe/frappe-bench/env/bin/bench worker --queue long
priority=50
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=frappe

[program:scheduler]
command=/home/frappe/frappe-bench/env/bin/bench schedule
priority=60
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=frappe
